version: '3.2'

services:

  vault:
    image: vault:latest
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: supersecret
    cap_add:
      - IPC_LOCK
    expose:
      - 8200

  supersecret:
    build: ./
    image: algolia/supersecretmessage:latest
    container_name: supersecret
    environment:
      DOMAIN: "${DOMAIN}"
      VAULT_ADDR: http://vault:8200
      VAULT_PREFIX: cubbyhole/
      VAULT_TOKEN: supersecret
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - vault

